export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const IS_LOADING_GET_ORDER = "IS_LOADING_GET_ORDER";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const UPDATE_STATUS_ORDER = "UPDATE_STATUS_ORDER";
