export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_FORM_PRODUCT = "GET_FORM_PRODUCT";
export const IS_LOADING = "IS_LOADING";
export const IS_SUCCSESS = "IS_SUCCSESS";
