export const GET_DATA_FORM = "GET_DATA_FORM";
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const USER = "USER";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
export const GET_DATA_SIGNUP = "GET_DATA_SIGNUP";
export const SIGNUP_ACCOUNT = "SIGNUP_ACCOUNT";
export const SHOW_PASSWORD_ACCOUNT = "SHOW_PASSWORD_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";

export const GET_DATA_FORM_ADDRESS = "GET_DATA_FORM_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const FILL_DATA_FORM_ADDRESS = "FILL_DATA_FORM_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const SET_DAFAULT_ADDRESS = "SET_DAFAULT_ADDRESS";
